version: "3.8"
services:
 # Eureka Service
  eureka-server:
    image: trifang/eureka-server:1.0
    ports:
      - 8761:8761
    expose:
      # Opens port 8761 on the container
      - '8761'
    container_name: eureka-server
    networks:
      - internal_docker_network
 # Zuul Service
  eureka-zuul-service:
    image: trifang/eureka-zuul-service:1.0
    ports:
      - 8762:8762
    expose:
      # Opens port 8762 on the container
      - '8762'
    container_name: eureka-zuul-service
    links:
      - eureka-server
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - internal_docker_network
 # MySql Database
  docker-mysql:
    image: mysql:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=springstore_schema
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
    expose:
      - '3306'
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - internal_docker_network
    container_name: docker-mysql
# User Service
  user-service:
    image: trifang/user-service:1.0
    ports:
      - 8080:8080
    container_name: user-service
    build:
       context: ./
       dockerfile: Dockerfile
    depends_on:
      docker-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      eureka-zuul-service:
        condition: service_started
      zipkin:
        condition: service_started
    links:
      - docker-mysql
      - eureka-server
      - eureka-zuul-service
      - zipkin
    networks:
      - internal_docker_network
# Zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
      # Uncomment to enable self-tracing
      #- SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    # Uncomment to enable debug logging
    # command: --logging.level.zipkin2=DEBUG
    networks:
      - internal_docker_network  
networks:
   internal_docker_network:
