name: Build and test

on:
  push:
    branches:
      - "feature/github_workflow"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      SONAR_TOKEN: $SONAR_TOKEN
    steps:
      # Checkout the code as the first step.
      - name: Checkout
        uses: actions/checkout@v3
      # Build
      - name: Build
        run: |
          mvn -B -DskipTests clean package
      # Then run your tests!
      - name: Unit Tests
        run: |
          mvn test
      - name: Create Test reports folder
        run: |
          mkdir -p $CIRCLE_TEST_REPORTS/junit/
      - name: Save Test reports
        run: |
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
      - name: SonarCloud Analyze
        run: |
          mvn verify sonar:sonar -Dsonar.projectKey=springstoreorg_user-service